name: Test dotfiles on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run make
        run: make
        continue-on-error: false
        env:
          NIX_SKIP_INSTALL: "true"

      - name: Run tests
        run: make test

      - name: Report results
        if: success()
        run: echo "All tests passed successfully!"

      - name: Report failure
        if: failure()
        run: echo "Tests failed. Please check the logs above."
